proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/eivifj_dot@1.0.1
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/dotty@0.1.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/confucious@0.0.12
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/dot-prop@5.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/madlib-object-utils@0.1.6
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/merge@1.2.1
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/arr-flatten-unflatten@1.0.2
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/connie-lang@0.1.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/property-expr@2.0.2
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/nis-utils@0.6.10
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/nodee-utils@1.2.2
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/lodash.zipobjectdeep@4.4.2
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/irrelon-path@2.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/fastify@1.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/sailshq_lodash@3.10.2
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/linux-cmdline@1.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/node-forge@0.9.1
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/dot-notes@3.2.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/utilitify@1.0.2
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/deeply@2.0.3
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/controlled-merge@1.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/tiny-conf@1.1.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/deep-get-set@1.1.1
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/deeps@1.4.5
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/minimist@1.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/worksmith@1.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/deep-set@1.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/jquery@1.12.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/lutils-merge@0.2.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/set-value@3.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/lodash@4.6.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/ts-dot-prop@1.4.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/promisehelpers@0.0.5
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/utils-extend@1.0.8
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/extend@2.0.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/node-oojs@1.4.0
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/gammautils@0.0.81
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/casperjs@1.1.4/modules/utils.js
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/dojo@1.12.0/request/util.js
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/gedi@1.6.3
proto_pollution is detected in /home/lsong18/projs/newVulPackages/pp/packages/angular@1.6.6
