proto_pollution is detected in eivifj_dot@1.0.1
proto_pollution is detected in dotty@0.1.0
proto_pollution is detected in confucious@0.0.12
proto_pollution is detected in dot-prop@5.0.0
proto_pollution is detected in madlib-object-utils@0.1.6
proto_pollution is detected in merge@1.2.1
proto_pollution is detected in arr-flatten-unflatten@1.0.2
proto_pollution is detected in connie-lang@0.1.0
proto_pollution is detected in property-expr@2.0.2
proto_pollution is detected in nis-utils@0.6.10
proto_pollution is detected in nodee-utils@1.2.2
proto_pollution is detected in lodash.zipobjectdeep@4.4.2
proto_pollution is detected in irrelon-path@2.0.0
proto_pollution is detected in fastify@1.0.0
proto_pollution is detected in sailshq_lodash@3.10.2
proto_pollution is detected in linux-cmdline@1.0.0
proto_pollution is detected in node-forge@0.9.1
proto_pollution is detected in dot-notes@3.2.0
proto_pollution is detected in utilitify@1.0.2
proto_pollution is detected in deeply@2.0.3
proto_pollution is detected in controlled-merge@1.0.0
proto_pollution is detected in tiny-conf@1.1.0
proto_pollution is detected in deep-get-set@1.1.1
proto_pollution is detected in deeps@1.4.5
proto_pollution is detected in minimist@1.0.0
proto_pollution is detected in worksmith@1.0.0
proto_pollution is detected in deep-set@1.0.0
proto_pollution is detected in jquery@1.12.0
proto_pollution is detected in lutils-merge@0.2.0
proto_pollution is detected in set-value@3.0.0
proto_pollution is detected in lodash@4.6.0
proto_pollution is detected in ts-dot-prop@1.4.0
proto_pollution is detected in promisehelpers@0.0.5
proto_pollution is detected in utils-extend@1.0.8
proto_pollution is detected in extend@2.0.0
proto_pollution is detected in node-oojs@1.4.0
proto_pollution is detected in gammautils@0.0.81
proto_pollution is detected in casperjs@1.1.4/modules/utils.js
proto_pollution is detected in dojo@1.12.0/request/util.js
proto_pollution is detected in gedi@1.6.3
proto_pollution is detected in angular@1.6.6
